### ISSUE TITLE
Ending of part 2

### ISSUE THREAD

**Issue by philipcmonk** [knubie/learning-hoon#3]
I probably shouldn't write the explanation, because I like your style, but I can answer the question at the end of part 2.

In `$(a (add a 1))`, you'll notice that this isn't `%-`.  That would look like `($ (add a 1))`, except that doesn't actually work because the `$` is in the core, so it's not the whole gate.

The irregular syntax `a(b c, d e, f g, ...)` is the `%=` twig, so `$(a (add a 1))` is `%=($ a (add a 1))`.  You can look up the docs for that, but, in English, that's "produce $, except replace `a` in its subject with `(add a 1)`".  You can replace as many or as few things in the subject as you want, and this form works for more than just gates.  `=+(a=[b=1 c=2] a(b 0))` gives `[b=0 c=2]`, for example.

**Comment by knubie** [comment]
Thanks! This is a great explanation, I'll incorporate this into the post somehow.
